version: '3.8'
services:
  rails:
    build:
      context: ./rails-api
      dockerfile: Dockerfile.rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./rails-api:/app

  rust:
    build:
      context: ./rust-wallet
      dockerfile: Dockerfile.rust
    environment:
      - RUST_LOG=info

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=secure_wallet_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres-data:
